"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--a7rw)!gcro8)5bvb4&3ghvjw%7kct2k@rw-7e=f1(gmkzn0^u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #追加
    'rest_framework',
    'corsheaders',
    'expenses',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # 追加

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 追加
# Django REST Framework(REST APIの設定)の共通ルール 
REST_FRAMEWORK = {
    # 認証方法（ユーザーが誰かを判別）をSessionに統一
    # → Djangoの通常ログイン(/admin)の仕組みをそのまま使う
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],

    # 権限（アクセスして良いか）を「ログイン必須」にする
    #   → 原則として、ログインしている人だけAPIを使えるようにする
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

#追記 sta
# ==============================
# CORS設定
# ==============================

# React(localhost:5137)など、Djangoとは異なるオジリンからのAPIアクセスを許可する設定
# ブラウザによる「別ドメイン通信ブロック」を防ぐために必要。

# ※本番環境では必ず False にし、許可オリジンを限定すること。
CORS_ALLOW_ALL_ORIGINS = True
#追記 end


# 臨時追記 sta
# Cookie（セッション）を含むクロスオリジン通信を許可する設定。
# REACT 側の fetch で credentials: "include" を使う場合に必須。

# これが False のままだと、ログイン済みでも、API 側では「未ログイン」と判断される
# React（App.jsx）の「credentials: "include"」を正しく機能させるために必要
CORS_ALLOW_CREDENTIALS = True
# 臨時追記 end


"""
# 以下は臨時追記したものだったが、不要だったため、コメントアウト
# ==============================
# CSRF対策設定
# ==============================

# Django が「信頼してよいフロントエンドのURL」を指定する。
# セッション認証 + API通信を行う場合、React のURLを明示的に許可する必要がある。
#
# これを設定しないと、Post / PUT / DELETE などで 403 エラーになることがある。
# 実際、「"GET /api/ping/ HTTP/1.1" 403 58」というエラーになった。
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
]
"""


"""
# NOTE:
# React(5173) → Django(8000) のセッションCookie送信問題を疑い、
# SameSite/secure設定を一時的に追加したが、
# 原因は localhost と 127.0.0.1 の混在による Cookie 不送信だった。
# ホスト統一＋Cookie削除で解消したため、本設定は不要としてコメントアウト。
# ==============================
# セッション / CSRF Cookie 設定（開発用）
# ==============================

# React（localhost:5173）と Django（localhost:8000）は
# 「別オリジン」になるため、デフォルト設定では
# セッション Cookie がブラウザから送信されない。
#
# その結果、ログインしていても API 側では
# 「未ログイン」と判定され、403 エラーになる。
#
# 下記設定は、開発環境で React + Django を連携させるためのもの。
# ※ 本番環境では HTTPS 前提の設定に変更すること。

# セッション Cookie をクロスオリジン通信でも送信可能にする
SESSION_COOKIE_SAMESITE = "None"

# 開発環境（http）では Secure=False にする
# ※ 本番（https）では True にする
SESSION_COOKIE_SECURE = False

# CSRF Cookie も同様にクロスオリジン通信を許可
CSRF_COOKIE_SAMESITE = "None"

# 開発環境用（http）
CSRF_COOKIE_SECURE = False


"""