# Generated by Django 4.2.27 on 2025-12-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commuterpass',
            old_name='valid_end',
            new_name='valid_to',
        ),
    ]
